// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vjuzQF41Fh066frxjGbcD7ETa6kPJgc',
    appId: '1:864930463555:web:566a054a3c128721ce79f6',
    messagingSenderId: '864930463555',
    projectId: 'food-delivery-app-a6af9',
    authDomain: 'food-delivery-app-a6af9.firebaseapp.com',
    storageBucket: 'food-delivery-app-a6af9.appspot.com',
    measurementId: 'G-XGS899QWDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi9JYSJCg5pZx_R6IjDNUwPZqidGJsEN8',
    appId: '1:864930463555:android:18ae257507d4a6a0ce79f6',
    messagingSenderId: '864930463555',
    projectId: 'food-delivery-app-a6af9',
    storageBucket: 'food-delivery-app-a6af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbl_CBN5BG1N6od1NlE64EV-fU_B64Kg',
    appId: '1:864930463555:ios:49d67fd58df6dbb6ce79f6',
    messagingSenderId: '864930463555',
    projectId: 'food-delivery-app-a6af9',
    storageBucket: 'food-delivery-app-a6af9.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbl_CBN5BG1N6od1NlE64EV-fU_B64Kg',
    appId: '1:864930463555:ios:49d67fd58df6dbb6ce79f6',
    messagingSenderId: '864930463555',
    projectId: 'food-delivery-app-a6af9',
    storageBucket: 'food-delivery-app-a6af9.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_vjuzQF41Fh066frxjGbcD7ETa6kPJgc',
    appId: '1:864930463555:web:f36509a018b4b927ce79f6',
    messagingSenderId: '864930463555',
    projectId: 'food-delivery-app-a6af9',
    authDomain: 'food-delivery-app-a6af9.firebaseapp.com',
    storageBucket: 'food-delivery-app-a6af9.appspot.com',
    measurementId: 'G-6NL5J4ZGED',
  );
}
